version: '3.8'

services:
  mongo:
    image: mongo:8
    container_name: proyecto-backend
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network

  pokedex-completo-clase-2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    container_name: proyecto_backend_final
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    networks:
      - mongo-network

volumes:
  mongo-data:

networks:
  mongo-network:
    driver: bridge